# Linear Regression 

# Fitting a Line

You want to train a model that represents a linear relationships between the feature and target vector.
Use a linear regression (in scikit-learn, linear regression)

In [1]:
# Load Libraries

from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


`load_boston` has been removed from scikit-learn since version 1.2. So instead of that we are using California housing dataset

In [2]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [3]:
features = housing.data[:,0:2]
target = housing.target

In [5]:
# Create Linear Regression

regression = LinearRegression()
regression

LinearRegression()

In [6]:
# Fit the Linear Regression

model = regression.fit(features, target)
model

LinearRegression()

# Formula

B0(beta knot), also called bias or intercept, can be viewed using intercept_:

In [7]:
# view the intercept

model.intercept_

-0.1018903275908265

B1(Beta one) and B2(Beta two) are shown using coef_:

In [8]:
# First value in the target vector multiplied by 1000

target[0]*1000

4526.0

In [9]:
# Predict the target value of the first observation, multiplied by 1000

model.predict(features)[0]*1000

4207.126263821179

In [10]:
# View the feature coefficients

model.coef_

array([0.43169191, 0.01744134])

# Handling Interactive Effects

You have a feature whose effect on target variabe on another feature
Create an interactions term to capture that dependence using scikit-learns's Polynomial Features

In [12]:
# Load Libraries
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import PolynomialFeatures

In [14]:
#Load data with ony two features 
housing = fetch_california_housing()
features = housing.data[:,0:2]
target  = housing.target

In [15]:
# Create interaction term
interaction = PolynomialFeatures(degree=3, include_bias=False, interaction_only=True)
features_interaction = interaction.fit_transform(features)

In [16]:
# Create Linear Regression
regression = LinearRegression()

In [17]:
# Fit the linear regression
model = regression.fit(features_interaction, target)

In [21]:
features_interaction

array([[  8.3252,  41.    , 341.3332],
       [  8.3014,  21.    , 174.3294],
       [  7.2574,  52.    , 377.3848],
       ...,
       [  1.7   ,  17.    ,  28.9   ],
       [  1.8672,  18.    ,  33.6096],
       [  2.3886,  16.    ,  38.2176]])

In [22]:
features_interaction[0]

array([  8.3252,  41.    , 341.3332])

In [23]:
# view the features for first observation
features[0]

array([ 8.3252, 41.    ])

In [25]:
# import library

import numpy as np

# For each observation, multiply the values of the first and second feature

interaction_term = np.multiply(features[:,0], features[:,1])

In [26]:
# view interaction term for first observation
interaction_term[0]

341.33320000000003

# Fitting a Non - Linear Relationship

You want to model a non-linear relationship
Create a polynomial regression by including polynomial features in a linear regression

In [1]:
# load Library

from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import PolynomialFeatures

In [3]:
# Load data with one feature for better understanding

housing = fetch_california_housing()
features = housing.data[:,0:1]
target = housing.target

In [4]:
# Create polynomial features x^2 and X^3

polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

In [5]:
# Create linear regression
regression = LinearRegression()


In [6]:
# Fit the linear regression

model = regression.fit(features_polynomial, target)

In [7]:
# view the first observation
features[0]

array([8.3252])

In [8]:
# view the first observation raised to the second power X^2 to cross verify
features[0]**2

array([69.30895504])

In [9]:
# view the first observation raised to the third power X^3 to cross verify
features[0]**3

array([577.0109125])

In [10]:
# now to get the first observation values for X,X^2 and X^3
features_polynomial[0]

array([  8.3252    ,  69.30895504, 577.0109125 ])

# Reducing Variance Through Regularization

you want to reduce the variance of your linear regression model.
Use a learning algorithm that includes a shrinkage penalty (also called regularization) like ridge regression and lasso regression.

In [11]:
# Load Libraries

from sklearn.linear_model import Ridge
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

In [ ]:
# Load data 

housing = fetch_california_housing()
features = housing.data
target = housing.target

In [12]:
# Standarize features

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [13]:
# Create ridge regression with an alpha value
regression = Ridge(alpha = 0.5)

In [14]:
# fit the linear regression 
model = regression.fit(features_standardized, target)

# formula

In [15]:
model

Ridge(alpha=0.5)

scikit learn includes a RidgeCV method that allows us to select the ideal value for alpha(a)

In [16]:
# Load library
from sklearn.linear_model import RidgeCV

# create ridge regression with three alpha values

regr_cv = RidgeCV(alphas = [0.1,1.0,10.0])

In [17]:
# fit the linear regression
model_cv = regr_cv.fit(features_standardized, target)

In [18]:
# View coefficients
model_cv.coef_

array([0.79395092])

In [19]:
# We can easily view the best mpdels's alpha value
# view alpha

model_cv.alpha_

1.0