Every algorithm involved in scikit learn via an 'Estimator'
First Import the model general form is given below

from sklearn.family import model

for example:
    
from sklearn.linear_model import LinearRegression

In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
model = LinearRegression()
print(model)

LinearRegression()


In [3]:
LinearRegression(copy_X = True, fit_intercept=True, normalize=True)

TypeError: LinearRegression.__init__() got an unexpected keyword argument 'normalize'

# program for Training and Splitting

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
# getting or creating the datas
X, y = np.arange(10).reshape((5, 2)),range(5)

In [6]:
print(X)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
list(y)

[0, 1, 2, 3, 4]

In [8]:
# splitting the datas into train and test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
X_train

array([[2, 3],
       [4, 5],
       [0, 1]])

In [10]:

y_train

[1, 2, 0]

In [11]:
X_test

array([[8, 9],
       [6, 7]])

In [12]:



y_test

[4, 3]

In [13]:
# Now we can train or fit the split data

model.fit(X_train, y_train)

LinearRegression()

 Model has fit and trained on training data
model is ready to predict labels or values on the test set

In [14]:
# Now we get predicted values by using the predict method

predictions = model.predict(X_test)
predictions

array([4., 3.])

# Loading a data with scikit learn

In [15]:
import numpy as np
import pandas as pd


In [16]:
# here we are going to use popular pre loaded datasets to use

from sklearn import datasets
digits = datasets.load_digits()
features = digits.data
target = digits.target

In [17]:
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [18]:
features

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [19]:
target

array([0, 1, 2, ..., 8, 9, 8])

# Creating a simultated dataset
 or how to create a own dataset

In [20]:
from sklearn.datasets import make_regression

In [21]:
features, target, coefficients = make_regression(
    n_samples=100,
    n_features=3,
    n_informative=3,
    n_targets=1,
    bias=0.0,
    effective_rank=None,
    tail_strength=0.5,
    noise=0.0,
    shuffle=True,
    coef=True,
    random_state=1,
)

In [22]:
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [ ]:
# if we are interested in creating a simulted dataset for classification, we can use make_classification


In [23]:
# first load the library

from sklearn.datasets import make_classification

In [24]:
# generate features matrix and target vector

features, target = make_classification(n_samples = 100,
n_features = 3,
n_informative = 3,
n_redundant = 0,
n_classes = 2,
weights = [.25, .75],
random_state = 1)
# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])                                     

Feature Matrix
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target Vector
 [1 0 0]


In [ ]:
# finally , if we want a dataset designed to work well clusttering techniques, scikitlearn offers make_blobs

In [25]:

# load the library

from sklearn.datasets import make_blobs


In [26]:
# Generate feature matrix and target matrix

features, target = make_blobs(n_samples = 100,
n_features = 2,
centers = 3,
cluster_std = 0.5,
shuffle = True,
random_state = 1)

# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ -1.22685609   3.25572052]
 [ -9.57463218  -4.38310652]
 [-10.71976941  -4.20558148]]
Target Vector
 [0 1 1]


# Data Wrangling 

In [ ]:
# load the library 

import pandas as pd

In [ ]:
# create url

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

# load data as dataframe
dataframe = pd.read_csv(url)

# to get the first 5 rows
dataframe.head()

# Creating a Data Frame
pandas has many methods of creating a new DataFrame object. One easy method is to create an empty data frame using DataFrame and then define each column separately:

In [27]:
# Load library
import pandas as pd
# Create DataFrame
dataframe = pd.DataFrame()
# Add columns
dataframe['Name'] = ['Jacky Jackson', 'Steven Stevenson']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]
# Show DataFrame
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [28]:
# Alternatively, once we created a Datframe object, we can append new rows to the bottom

# create row
new_person = pd.Series(['Molly Mooney', 40, True], index = ['Name', 'Age', 'Driver'])

# Append row
dataframe.append(new_person, ignore_index = True)

C:\Users\Tamilarasu16\AppData\Local\Temp\ipykernel_11796\2307538769.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe.append(new_person, ignore_index = True)


Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

# Describing the Data

In [29]:
# create url

dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')

# to get the first 2 rows
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [30]:
# to get the shapes of the dataset

dataframe.shape

(1313, 6)

In [31]:
# to get the descriptive statistics for any numeric columns using describe

dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# Navigating Dataframes

In [32]:
dataframe.iloc[0]

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: 0, dtype: object

In [33]:
# to get 1 to 3 rd row

dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [34]:
# to get 0 to 3 rd row

dataframe.iloc[:4]

Name PClass   Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.0  female   
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1

In [35]:
# Set index

dataframe = dataframe.set_index(dataframe['Name'])

# show row

dataframe.loc['Allen, Miss Elisabeth Walton']

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: Allen, Miss Elisabeth Walton, dtype: object

# Selecting rows based on conditions

In [36]:
# show top rows where column 'sex' is female

dataframe[dataframe['Sex'] == 'female'].head(2)

Name PClass   Age  \
Name                                                                      
Allen, Miss Elisabeth Walton  Allen, Miss Elisabeth Walton    1st  29.0   
Allison, Miss Helen Loraine    Allison, Miss Helen Loraine    1st   2.0   

                                 Sex  Survived  SexCode  
Name                                                     
Allen, Miss Elisabeth Walton  female         1        1  
Allison, Miss Helen Loraine   female         0        1

In [37]:
dataframe[dataframe['Sex'] == 'female']

Name  \
Name                                                                                           
Allen, Miss Elisabeth Walton                                    Allen, Miss Elisabeth Walton   
Allison, Miss Helen Loraine                                      Allison, Miss Helen Loraine   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)  Allison, Mrs Hudson JC (Bessie Waldo Daniels)   
Andrews, Miss Kornelia Theodosia                            Andrews, Miss Kornelia Theodosia   
Appleton, Mrs Edward Dale (Charlotte Lamson)    Appleton, Mrs Edward Dale (Charlotte Lamson)   
...                                                                                      ...   
Vestrom, Miss Hulda Amanda Adolfina                      Vestrom, Miss Hulda Amanda Adolfina   
Wilkes, Mrs Ellen                                                          Wilkes, Mrs Ellen   
Yasbeck, Mrs Antoni                                                      Yasbeck, Mrs Antoni   
Zabour, Miss Hileni                                                      Zabour, Miss Hileni   
Zabour, Miss Tamini                                                      Zabour, Miss Tamini   

                                              PClass   Age     Sex  Survived  \
Name                                                                           
Allen, Miss Elisabeth Walton                     1st  29.0  female         1   
Allison, Miss Helen Loraine                      1st   2.0  female         0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female         0   
Andrews, Miss Kornelia Theodosia                 1st  63.0  female         1   
Appleton, Mrs Edward Dale (Charlotte Lamson)     1st  58.0  female         1   
...                                              ...   ...     ...       ...   
Vestrom, Miss Hulda Amanda Adolfina              3rd  14.0  female         0   
Wilkes, Mrs Ellen                                3rd  45.0  female         1   
Yasbeck, Mrs Antoni                              3rd  15.0  female         1   
Zabour, Miss Hileni                              3rd   NaN  female         0   
Zabour, Miss Tamini                              3rd   NaN  female         0   

                                               SexCode  
Name                                                    
Allen, Miss Elisabeth Walton                         1  
Allison, Miss Helen Loraine                          1  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)        1  
Andrews, Miss Kornelia Theodosia                     1  
Appleton, Mrs Edward Dale (Charlotte Lamson)         1  
...                                                ...  
Vestrom, Miss Hulda Amanda Adolfina                  1  
Wilkes, Mrs Ellen                                    1  
Yasbeck, Mrs Antoni                                  1  
Zabour, Miss Hileni                                  1  
Zabour, Miss Tamini                                  1  

[462 rows x 6 columns]

In [38]:
dataframe[dataframe['Sex'] == 'female']['Name']

Name
Allen, Miss Elisabeth Walton                                      Allen, Miss Elisabeth Walton
Allison, Miss Helen Loraine                                        Allison, Miss Helen Loraine
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    Allison, Mrs Hudson JC (Bessie Waldo Daniels)
Andrews, Miss Kornelia Theodosia                              Andrews, Miss Kornelia Theodosia
Appleton, Mrs Edward Dale (Charlotte Lamson)      Appleton, Mrs Edward Dale (Charlotte Lamson)
                                                                     ...                      
Vestrom, Miss Hulda Amanda Adolfina                        Vestrom, Miss Hulda Amanda Adolfina
Wilkes, Mrs Ellen                                                            Wilkes, Mrs Ellen
Yasbeck, Mrs Antoni                                                        Yasbeck, Mrs Antoni
Zabour, Miss Hileni                                                        Zabour, Miss Hileni
Zabour, Miss Tamini                          

In [39]:
dataframe[dataframe['Sex'] == 'female']['Name'].head()

Name
Allen, Miss Elisabeth Walton                                      Allen, Miss Elisabeth Walton
Allison, Miss Helen Loraine                                        Allison, Miss Helen Loraine
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    Allison, Mrs Hudson JC (Bessie Waldo Daniels)
Andrews, Miss Kornelia Theodosia                              Andrews, Miss Kornelia Theodosia
Appleton, Mrs Edward Dale (Charlotte Lamson)      Appleton, Mrs Edward Dale (Charlotte Lamson)
Name: Name, dtype: object

In [40]:
# to do multiple conditions

dataframe[(dataframe['Sex'] == 'female') & (dataframe['Age'] >= 65)]

Name  \
Name                                                                                                    
Crosby, Mrs Edward Gifford (Catherine Elizabeth...  Crosby, Mrs Edward Gifford (Catherine Elizabet...   

                                                   PClass   Age     Sex  \
Name                                                                      
Crosby, Mrs Edward Gifford (Catherine Elizabeth...    1st  69.0  female   

                                                    Survived  SexCode  
Name                                                                   
Crosby, Mrs Edward Gifford (Catherine Elizabeth...         1        1

In [41]:
# to reset the index 

dataframe.reset_index(drop=True)

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92    male   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00    male   
1309                         Zakarian, Mr Maprieder    3rd  26.00    male   
1310                               Zenni, Mr Philip    3rd  22.00    male   
1311                               Lievens, Mr Rene    3rd  24.00    male   
1312                                 Zimmerman, Leo    3rd  29.00    male   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

# Replacing values

In [42]:
dataframe['Sex'].replace('female','woman').head(2)

Name
Allen, Miss Elisabeth Walton    woman
Allison, Miss Helen Loraine     woman
Name: Sex, dtype: object

In [43]:
dataframe['Sex'].replace(['female','male'],['woman','man']).head()

Name
Allen, Miss Elisabeth Walton                     woman
Allison, Miss Helen Loraine                      woman
Allison, Mr Hudson Joshua Creighton                man
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    woman
Allison, Master Hudson Trevor                      man
Name: Sex, dtype: object

In [44]:
# replace values

dataframe.replace(1, 'one').head()

Name  \
Name                                                                                           
Allen, Miss Elisabeth Walton                                    Allen, Miss Elisabeth Walton   
Allison, Miss Helen Loraine                                      Allison, Miss Helen Loraine   
Allison, Mr Hudson Joshua Creighton                      Allison, Mr Hudson Joshua Creighton   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)  Allison, Mrs Hudson JC (Bessie Waldo Daniels)   
Allison, Master Hudson Trevor                                  Allison, Master Hudson Trevor   

                                              PClass   Age     Sex Survived  \
Name                                                                          
Allen, Miss Elisabeth Walton                     1st  29.0  female      one   
Allison, Miss Helen Loraine                      1st   2.0  female        0   
Allison, Mr Hudson Joshua Creighton              1st  30.0    male        0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female        0   
Allison, Master Hudson Trevor                    1st  0.92    male      one   

                                              SexCode  
Name                                                   
Allen, Miss Elisabeth Walton                      one  
Allison, Miss Helen Loraine                       one  
Allison, Mr Hudson Joshua Creighton                 0  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)     one  
Allison, Master Hudson Trevor                       0

In [45]:
dataframe.reset_index(drop=True, inplace=True)

In [46]:
# replace also accepts regular expressions

# replace values

dataframe.replace(r'1st', 'First', regex = True).head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton  First  29.0  female         1        1
1   Allison, Miss Helen Loraine  First   2.0  female         0        1

# Renaming column

In [47]:
# rename column

dataframe.rename(columns={'PClass': 'Passenger Class'}).head()

Name Passenger Class    Age  \
0                   Allen, Miss Elisabeth Walton             1st  29.00   
1                    Allison, Miss Helen Loraine             1st   2.00   
2            Allison, Mr Hudson Joshua Creighton             1st  30.00   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)             1st  25.00   
4                  Allison, Master Hudson Trevor             1st   0.92   

      Sex  Survived  SexCode  
0  female         1        1  
1  female         0        1  
2    male         0        0  
3  female         0        1  
4    male         1        0

In [48]:
 # Rename multiple columns
    
dataframe.rename(columns={'PClass':'Passenger Class', 'Sex':'Gender'}).head()

Name Passenger Class    Age  \
0                   Allen, Miss Elisabeth Walton             1st  29.00   
1                    Allison, Miss Helen Loraine             1st   2.00   
2            Allison, Mr Hudson Joshua Creighton             1st  30.00   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)             1st  25.00   
4                  Allison, Master Hudson Trevor             1st   0.92   

   Gender  Survived  SexCode  
0  female         1        1  
1  female         0        1  
2    male         0        0  
3  female         0        1  
4    male         1        0

In [49]:
# this helpful snippet of code creates a dictionary with the old column names as keys and empty strings as values

# load library 
import collections

# create dictionary
column_names = collections.defaultdict(str)

# create keys
for name in dataframe.columns:
    column_names[name]
    
# show dictonary
column_names


defaultdict(str,
            {'Name': '',
             'PClass': '',
             'Age': '',
             'Sex': '',
             'Survived': '',
             'SexCode': ''})

# finding the Minimum, Maximum, Sum, Averag and count

In [50]:
# calculate statistics

print('Maximum', dataframe['Age'].max())
print('Minimum', dataframe['Age'].min())
print('Mean', dataframe['Age'].mean())
print('Sum', dataframe['Age'].sum())
print('Count', dataframe['Age'].count())

Maximum 71.0
Minimum 0.17
Mean 30.397989417989418
Sum 22980.88
Count 756


In [51]:
# show counts

dataframe.count()

Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

In [52]:
# Select unique values

dataframe['Sex'].unique()

array(['female', 'male'], dtype=object)

In [53]:
# show counts

dataframe['Sex'].value_counts()

male      851
female    462
Name: Sex, dtype: int64

In [54]:
dataframe['PClass'].value_counts()

3rd    711
1st    322
2nd    279
*        1
Name: PClass, dtype: int64

# Handling Missing Values

In [55]:
# select missing values

dataframe[dataframe['Age'].isnull()]

Name PClass  Age     Sex  Survived  SexCode
12    Aubert, Mrs Leontine Pauline    1st  NaN  female         1        1
13        Barkworth, Mr Algernon H    1st  NaN    male         1        0
14              Baumann, Mr John D    1st  NaN    male         0        0
29         Borebank, Mr John James    1st  NaN    male         0        0
32              Bradley, Mr George    1st  NaN    male         1        0
...                            ...    ...  ...     ...       ...      ...
1300         Wiseman, Mr Phillippe    3rd  NaN    male         0        0
1302             Yalsevac, Mr Ivan    3rd  NaN    male         1        0
1305            Youssef, Mr Gerios    3rd  NaN    male         0        0
1306           Zabour, Miss Hileni    3rd  NaN  female         0        1
1307           Zabour, Miss Tamini    3rd  NaN  female         0        1

[557 rows x 6 columns]

In [57]:
# Attempt to replace values with NaN

dataframe['Sex'] = dataframe['Sex'].replace['male', np.NaN]

TypeError: 'method' object is not subscriptable

In [58]:
# to have full functionality with NaN we need to import the Numpy library first
    
# load library

import numpy as np

# Replace values with NaN

dataframe['Sex'] = dataframe['Sex'].replace('male',np.nan)


In [59]:
dataframe['Sex'] = dataframe['Sex'].replace('NaN', 'male')

In [60]:
dataframe

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92     NaN   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00     NaN   
1309                         Zakarian, Mr Maprieder    3rd  26.00     NaN   
1310                               Zenni, Mr Philip    3rd  22.00     NaN   
1311                               Lievens, Mr Rene    3rd  24.00     NaN   
1312                                 Zimmerman, Leo    3rd  29.00     NaN   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

# deleting a Column

In [ ]:
# The best way to delete a column is to use drop with the parameter axis = 1 (i.e, the column axis)

In [61]:
# delete column

dataframe.drop('Age', axis=1).head()

Name PClass     Sex  Survived  \
0                   Allen, Miss Elisabeth Walton    1st  female         1   
1                    Allison, Miss Helen Loraine    1st  female         0   
2            Allison, Mr Hudson Joshua Creighton    1st     NaN         0   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  female         0   
4                  Allison, Master Hudson Trevor    1st     NaN         1   

   SexCode  
0        1  
1        1  
2        0  
3        1  
4        0

In [62]:
# delete multiple columns

dataframe.drop(['Age','Sex'], axis=1).head()

Name PClass  Survived  SexCode
0                   Allen, Miss Elisabeth Walton    1st         1        1
1                    Allison, Miss Helen Loraine    1st         0        1
2            Allison, Mr Hudson Joshua Creighton    1st         0        0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st         0        1
4                  Allison, Master Hudson Trevor    1st         1        0

In [63]:

dataframe.columns

Index(['Name', 'PClass', 'Age', 'Sex', 'Survived', 'SexCode'], dtype='object')

In [64]:
# drop columns using index

dataframe.drop(dataframe.columns[1],axis=1).head()

Name    Age     Sex  Survived  \
0                   Allen, Miss Elisabeth Walton  29.00  female         1   
1                    Allison, Miss Helen Loraine   2.00  female         0   
2            Allison, Mr Hudson Joshua Creighton  30.00     NaN         0   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)  25.00  female         0   
4                  Allison, Master Hudson Trevor   0.92     NaN         1   

   SexCode  
0        1  
1        1  
2        0  
3        1  
4        0

# deleting a row

In [65]:
# delete a row

dataframe[dataframe['Sex'] != 'male'].head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92     NaN   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [66]:
dataframe[dataframe['Name'] != 'Allison, Miss Helen Loraine'].head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92     NaN   
5                             Anderson, Mr Harry    1st  47.00     NaN   

   Survived  SexCode  
0         1        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0

In [67]:
dataframe[dataframe.index != 0].head()

Name PClass    Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92     NaN   
5                             Anderson, Mr Harry    1st  47.00     NaN   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0

#  Dropping duplicate rows

In [68]:
dataframe.drop_duplicates()

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92     NaN   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00     NaN   
1309                         Zakarian, Mr Maprieder    3rd  26.00     NaN   
1310                               Zenni, Mr Philip    3rd  22.00     NaN   
1311                               Lievens, Mr Rene    3rd  24.00     NaN   
1312                                 Zimmerman, Leo    3rd  29.00     NaN   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

In [69]:
# to check

len(dataframe)


1313

In [70]:
len(dataframe.drop_duplicates())

1313

In [71]:
# subset fuction

dataframe.drop_duplicates(subset=['Sex'])

Name PClass   Age     Sex  Survived  SexCode
0         Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
2  Allison, Mr Hudson Joshua Creighton    1st  30.0     NaN         0        0

In [72]:
# subset fuction by using keep parameter

dataframe.drop_duplicates(subset=['Sex'], keep = 'last')

Name PClass   Age     Sex  Survived  SexCode
1307  Zabour, Miss Tamini    3rd   NaN  female         0        1
1312       Zimmerman, Leo    3rd  29.0     NaN         0        0

# Grouping Rows by Values

In [73]:
# Group rows by the values of the column 'Sex',  calculate mean of each group

dataframe.groupby('Sex')['Age'].mean() # Note: Aggregate function should be used after the groupby function , otherwise itll not work

Sex
female    29.396424
Name: Age, dtype: float64

In [74]:
# Eg

dataframe.groupby('Sex')

In [75]:
# group rows, count rows

dataframe.groupby('Survived')['Name'].count()

Survived
0    863
1    450
Name: Name, dtype: int64

In [76]:
dataframe.groupby(['Sex','Survived'])['Age'].mean()

Sex     Survived
female  0           24.901408
        1           30.867143
Name: Age, dtype: float64

# Grouping Rows by time

In [77]:
# Create date range

time_index = pd.date_range('06/06/2017', periods=100000, freq = '30s')

In [78]:
# create dataframe

dataframe = pd.DataFrame(index=time_index)

In [79]:
# Create column of random values

dataframe['Sale_Amount'] = np.random.randint(1, 10, 100000)

In [80]:
dataframe.head()

Sale_Amount
2017-06-06 00:00:00            6
2017-06-06 00:00:30            5
2017-06-06 00:01:00            8
2017-06-06 00:01:30            5
2017-06-06 00:02:00            7

In [81]:
dataframe.tail()

Sale_Amount
2017-07-10 17:17:30            4
2017-07-10 17:18:00            8
2017-07-10 17:18:30            5
2017-07-10 17:19:00            9
2017-07-10 17:19:30            4

In [82]:
# Group rows by week, calculate sum per week

dataframe.resample('W').sum()

Sale_Amount
2017-06-11        86117
2017-06-18       101091
2017-06-25       100557
2017-07-02       100844
2017-07-09       100653
2017-07-16        10230

In [83]:
# Group by two weeks, calculate mean

dataframe.resample('2W').mean()

Sale_Amount
2017-06-11     4.983623
2017-06-25     5.001190
2017-07-09     4.997445
2017-07-23     4.918269

In [84]:
dataframe.resample('2W').sum()

Sale_Amount
2017-06-11        86117
2017-06-25       201648
2017-07-09       201497
2017-07-23        10230

In [85]:
# group by month, count rows

dataframe.resample('M').count()

Sale_Amount
2017-06-30        72000
2017-07-31        28000

In [86]:
# group by month, count rows

dataframe.resample('M', label='left').count()

Sale_Amount
2017-05-31        72000
2017-06-30        28000

#  Looping over a column

In [87]:
# create url

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

# load data as dataframe
dataframe = pd.read_csv(url)

# to get the first 5 rows
dataframe.head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [88]:
# print the first two roes in upper case

for i in dataframe['Name'][0:2]:
    print(i.upper())

ALLEN, MISS ELISABETH WALTON
ALLISON, MISS HELEN LORAINE


In [89]:
# In addition to loops (often called for loops),  we can also use list comprehensions

[i.upper() for i in dataframe['Name'][0:2]]

['ALLEN, MISS ELISABETH WALTON', 'ALLISON, MISS HELEN LORAINE']

# Applying a function over all elements in a column



In [90]:
# create function

def uppercase(x):
    return x.upper()

In [91]:
# apply function , show the first 3 rows

dataframe['Name'].apply(uppercase)[0:2]

0    ALLEN, MISS ELISABETH WALTON
1     ALLISON, MISS HELEN LORAINE
Name: Name, dtype: object

# Applying a Function to Groups

In [92]:
# Group rows, apply function to groups

dataframe.groupby('Sex').apply(lambda x: x.count())

Name  PClass  Age  Sex  Survived  SexCode
Sex                                              
female   462     462  288  462       462      462
male     851     851  468  851       851      851

# Handling Numerical Data

# Rescaling a feature



In [93]:
# use scikit-learn's MinMaxScaler to rescale a feature array

import pandas as pd
import numpy as np

In [94]:
# load libraries

from sklearn import preprocessing

# create feature

Feature = np.array([[-500.5],
                   [-100.1],
                   [0],
                   [100.1],
                   [900.9]])

# create scaler

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

# Scale feature

scaled_feature = minmax_scale.fit_transform(Feature)

In [95]:
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# Standardizing a Feature

In [96]:
# Load library 

import numpy as np
from sklearn import preprocessing

# Creating a feature

X = np.array([[-1000.1],
              [-200.2],
             [500.5],
             [600.6],
             [9000.9]])

# create scaler

scaler = preprocessing.StandardScaler()

# transform the feature 

standardized = scaler.fit_transform(X)

In [97]:
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [98]:
# to check if the standardization is correct or not

# use their mean and standard deviation to confirm, because if we do satndardization we need to get mean as 0 and std as 1


print('Mean', round(standardized.mean()))
print('Standard Deviation', standardized.std())

Mean 0
Standard Deviation 1.0


If our data has significant outliers, it can negatively impact our standardization by affecting the fatures mean and variance.
In this scenario, it is often helpful to instead rescale the feature using the median and quartile range. In scikit - learn, we do this using RobustScaler method

In [99]:
# Create Scaler
robust_scaler = preprocessing.RobustScaler()

# transform feature
robust_scaler.fit_transform(X)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

# Normalizing Observation

In [100]:
# load libraries

from sklearn.preprocessing import Normalizer

# create feature matrix

features = np.array([[0.5, 0.5],
                    [1.1, 3.4],
                    [1.5, 20.2],
                    [1.63, 34.4],
                    [10.9, 3.3]])

# create normalizer 
normalizer = Normalizer(norm = 'l2')

# transform feature matrix

normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

Alternatively we can specify Manhattan norm('l1')

In [102]:
# transform feature matrix
features_11_norm = Normalizer(norm='l1').transform(features)

# show feature matrix
features_11_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [105]:
features_l1_norm = Normalizer(norm='l1')
features_l1_norm.transform(features)

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [ ]:
# to check, 

print('Sum of the first observation\'s values:', 
     features_11_norm[0, 0] + features_11_norm[0, 1])

# Generating Polynomial and Interaction Features

Even though some choose to create polynomial and interaction features manually, scikit-learn offers a built-in method

In [106]:
# load libraries

import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [107]:
# create features

features = np.array([[2, 3],
                    [2, 3],
                    [2, 3]])

In [108]:
# create polynominal features object 

polynominal_interaction = PolynomialFeatures(degree=2, include_bias=False)

# create polynominal features
polynominal_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [109]:
# we can restrict the features created to only interaction features by setting interaction_only to True

interaction = PolynomialFeatures(degree=2,
interaction_only = True, include_bias=False)
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

# Transforming Features

In [110]:
# load libraries

import numpy as np
from sklearn.preprocessing import FunctionTransformer

# create a feature matrix
features = np.array([[2, 3],
                    [2, 3],
                    [2, 3]])

# Define a simple function
def add_ten(x):
    return x + 10

# Create transformer
ten_transformer = FunctionTransformer(add_ten)

# Transform feature matrix
ten_transformer.transform(features)




array([[12, 13],
       [12, 13],
       [12, 13]])

we can create the same transformation in pandas using apply method



In [111]:
# load library

import pandas as pd


In [112]:
# Create DataFrame
df = pd.DataFrame(features, columns=['feature_1', 'feature_2'])

# apply function
df.apply(add_ten)

feature_1  feature_2
0         12         13
1         12         13
2         12         13

#  Dectecting Outlier

In [113]:
# load libraries

import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

# create stimulated data

features, _ = make_blobs(n_samples=10,
                        n_features=2,
                        centers=1,
                        random_state=1)

# Replace the first observation with extreme values

features[0,0] = 10000
features[0,1] = 10000
outlier_detector = EllipticEnvelope(contamination=.1)

# fit detector

outlier_detector.fit(features)

# Predict outliers

outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [114]:
# we can use interquartile range (IQR)

def indices_of_outliers(x):
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    return np.where((x > upper_bound) | (x < lower_bound))

# run function

indices_of_outliers(features)

(array([0, 0], dtype=int64), array([0, 1], dtype=int64))

In [115]:
features = features[:,0]

In [116]:
features

array([ 1.00000000e+04, -2.76017908e+00, -1.61734616e+00, -5.25790464e-01,
        8.52518583e-02, -7.94152277e-01, -1.34052081e+00, -1.98197711e+00,
       -2.18773166e+00, -1.97451969e-01])

# Handling Outliers

In [ ]:
 # we have three strategies to handle the outliers

In [117]:
# first we can drop them

# load library

import pandas as pd

# craete dataframe

houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_feet'] = [1500, 2500, 1500, 40000]

# filter obsevation

houses[houses['Bathrooms'] < 20]

Price  Bathrooms  Square_feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

In [118]:
# Second stratergey, we can mark them as a oulier and include it as a feature

# load library
import numpy as np

# Create feature based on boolean condition
houses['Outlier'] = np.where(houses['Bathrooms']<20,0,1)

# show data
houses

Price  Bathrooms  Square_feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        40000        1

In [119]:
# Finally, we can transform the feature to dampen the effect of the outlier

# Log feature
houses['Log_of_Square_Feet'] = [np.log(x) for x in houses['Square_feet']]

# show data
houses

Price  Bathrooms  Square_feet  Outlier  Log_of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        40000        1           10.596635

# Discretizating Features

Depending upon how you want to break up the data, thre are two techniques we can use.
1) we can binarize the feature according to some threshold
2) We can digitize

In [120]:
# Load libraries
import numpy as np
from sklearn.preprocessing import Binarizer

# creating a feature
age = np.array([[6],
               [12],
               [20],
               [36],
               [65]])

# create binarizer
binarizer = Binarizer(18)

# transform feature
binarizer.fit_transform(age)

TypeError: Binarizer.__init__() takes 1 positional argument but 2 were given

Second we can break up numerical features according to multiple thresholds

In [121]:
# Bin feature
np.digitize(age, bins=[20,30,64])

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

# Grouping observations using clustering

In [122]:
# load libraries
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# make stimulated feature matrix
features, _ = make_blobs(n_samples=50,
                        n_features=2,
                        centers=3,
                        random_state=1)

# create dataframe
dataframe = pd.DataFrame(features, columns = ['feature_1', 'feature_2'])

# make K means cluster
cluster = KMeans(3, random_state=0)

# fit cluster
cluster.fit(features)

# Predict values
dataframe['Group'] = cluster.predict(features)

# show observation
dataframe

C:\Users\Tamilarasu16\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


feature_1  feature_2  Group
0   -9.877554  -3.336145      0
1   -7.287210  -8.353986      2
2   -6.943061  -7.023744      2
3   -7.440167  -8.791959      2
4   -6.641388  -8.075888      2
5   -0.794152   2.104951      1
6   -2.760179   5.551214      1
7   -9.946905  -4.590344      0
8   -0.525790   3.306599      1
9   -1.981977   4.022436      1
10  -5.865964  -7.968072      2
11  -6.834787  -7.391217      2
12  -6.749247 -10.175429      2
13 -10.752110  -2.700480      0
14  -8.508996  -8.657694      2
15  -2.330806   4.393825      1
16  -0.197452   2.346349      1
17   0.085252   3.645283      1
18 -10.206607  -3.366725      0
19  -9.158729  -3.022246      0
20  -1.340521   4.157119      1
21  -1.831988   3.528631      1
22  -9.806797  -1.853093      0
23  -0.758704   3.722762      1
24 -11.140231  -4.302691      0
25  -7.812137  -5.349845      2
26  -2.351221   4.009736      1
27  -6.878321  -7.743176      2
28  -1.782450   3.470720      1
29  -7.371086  -7.325253      2
30  -7.735544  -7.775664      2
31 -11.115023  -3.718933      0
32  -9.697542  -4.305598      0
33 -10.189548  -4.840978      0
34  -2.187732   3.333521      1
35  -2.346733   3.561284      1
36  -1.927448   4.936845      1
37 -10.744871  -2.260894      0
38  -6.866582  -8.034219      2
39  -7.512011  -6.928720      2
40  -6.904845  -7.277059      2
41  -1.617346   4.989305      1
42  -0.757969   4.908984      1
43  -9.484783  -4.251441      0
44  -7.408736  -8.109631      2
45  -9.509194  -4.028920      0
46  -8.337910  -3.211304      0
47  -9.712125  -3.068207      0
48  -8.866083  -2.433532      0
49  -7.684883  -7.455196      2

# Deleting Observations with missing values

In [123]:
# you need to delete the observations which are containing missing values

# Load library
import numpy as np

# create feature matrix
features = np.array([[1.1, 11,1],
                    [2.2, 22.2],
                    [3.3, 33.3],
                    [4.4, 44.4],
                    [np.nan, 55]])

# keep only observations that are not (denoted by ~) missing

features[~np.isnan(features).any(axis=1)]

C:\Users\Tamilarasu16\AppData\Local\Temp\ipykernel_11796\320422134.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  features = np.array([[1.1, 11,1],


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [124]:
# alternatively we can drop the missing values by using pandas

import pandas as pd

# load data
dataframe = pd.DataFrame(features, columns=['feature_1', 'feature_2'])

# remove the missing values in the dataset
dataframe.dropna()

ValueError: Shape of passed values is (5, 1), indices imply (5, 2)

# handling Categorical data

It is a qualitative data and it has two types
1. nominal--> No ordering
2. ordinal--> we can see natural ordering in this


# Encoding Nominal Categorical Features

  you have a feature with nominal classes that has no intrinstic ordering (eg) apple, pear, banana
  one hot encode the feature using scikit learns LabelBinarizer

In [127]:
# import libraries

import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

In [128]:
# Create feature
feature = np.array([['Texas'],
                   ['California'],
                   ['Texas'],
                   ['Delaware'],
                   ['Texas']])

In [129]:
# Create one hot encoder
one_hot = LabelBinarizer()

# Fit one hot encode feature
one_hot.fit_transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

we can use the class method to output the classes


In [130]:
# view feature classes

one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

If we want to reverse the one hot encoding we can use inverse_transform


In [131]:
# reverse one hot encoding

one_hot.inverse_transform(one_hot.transform(feature))

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

We can even use pandas to one-hot encode the feature

In [132]:
# import library
import pandas as pd

# create dummy variables from feature
pd.get_dummies(feature[:,0])

California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1

one helpful ability of scikit learn is to handle a situation where each observation lists multiple classes


In [133]:
# create multiclass feature

multiclass_feature = [('Texas', 'Florida'),
                     ('California', 'Alabama'),
                     ('Texas', 'Florida'),
                     ('Delaware', 'Florida'),
                     ('Texas', 'Alabama')]

# create multiclass one hot encoder
one_hot_multiclass = MultiLabelBinarizer()

# One_hot_multiclass featue
one_hot_multiclass.fit_transform(multiclass_feature)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [134]:
# view classes

one_hot_multiclass.classes_

array(['Alabama', 'California', 'Delaware', 'Florida', 'Texas'],
      dtype=object)

# Encoding Ordinal Categorical Features

Use Pandas DataFrame's replace method to transform string labels to numerical equivalents

In [135]:
# load library
import pandas as pd

# Create feature
dataframe = pd.DataFrame({'Score': ['Low', 'Low', 'Medium', 'Medium', 'High']})

# create mapper
scale_mapper = {'Low':1,
               'Medium':2,
               'High':3}

# Replace feature values with scale
dataframe['Score'].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

# Encoding Dictionaries of Features

In [136]:
# import library
from sklearn.feature_extraction import DictVectorizer

# create dictionary
data_dict = [{'Red':2, 'Blue':4},
            {'Red':4, 'Blue':3},
            {'Red':1, 'Yellow':2},
            {'Red':2, 'Yellow':2}]

# create dictionary vectorizer

dictvectorizer = DictVectorizer(sparse=False)

# Convert dictionary to feature matrix

features = dictvectorizer.fit_transform(data_dict)

# to get the feature matrix

features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [137]:
# what if we use sparse = true

# import library
from sklearn.feature_extraction import DictVectorizer

# create dictionary
data_dict = [{'Red':2, 'Blue':4},
            {'Red':4, 'Blue':3},
            {'Red':1, 'Yellow':2},
            {'Red':2, 'Yellow':2}]

# create dictionary vectoorizer

dictvectorizer = DictVectorizer(sparse=True)

# Convert dictionary to feature matrix

features = dictvectorizer.fit_transform(data_dict)

# to get the feature matrix

features

<4x3 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [138]:
# to get the feature names

feature_names = dictvectorizer.get_feature_names_out()
feature_names

array(['Blue', 'Red', 'Yellow'], dtype=object)

# Imputing Missing Class Values

In [ ]:
import numpy as np

X = np.array([[0, 2.10, 1.45],
             [1, 1.18, 1.33],
             [0, 1.22, 1.27],
             [1, -0.21, -1.19]])

print(X[:,1:])
print(X[:, 0])

In [139]:
# Load libraries
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# create feature matrix with missing values in the categorical feature
X = np.array([[0, 2.10, 1.45],
             [1, 1.18, 1.33],
             [0, 1.22, 1.27],
             [1, -0.21, -1.19]])

# create feature matrix with missing values in the categorial feature
X_with_nan = np.array([[np.nan, 0.87, 1.31],
                      [np.nan, -0.67, -0.22]])

# train KNN learner
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X[:,1:], X[:, 0])

# predict missing value class
imputed_values = trained_model.predict(X_with_nan[:,1:])

In [140]:
imputed_values

array([0., 1.])

In [141]:
imputed_values.reshape(-1,1)

array([[0.],
       [1.]])

In [142]:
# Join column of predicted class with their features
X_with_imputed = np.hstack((imputed_values.reshape(-1,1), X_with_nan[:,1:]))

In [143]:
X_with_imputed

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22]])

In [144]:
# Join two feature matrices
np.vstack((X_with_imputed, X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [145]:
# we need to know about hstack and vstack
# Vstack
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [146]:
b = np.array((2,2,2))

np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [147]:
# hstack

a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.array((2,2,2))
b

In [148]:
np.hstack((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [149]:
# it will throw an error, because we can't add here directly. we need to reshape it

b = np.array((2,2,2)).reshape(3,1)
b


array([[2],
       [2],
       [2]])

In [150]:
np.hstack((a,b))

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

An alternative solution is to fill in missing values with the features most frequent value by using Simple imputer

In [152]:
# load the required library
from sklearn.impute import SimpleImputer

# join the two feature matrix

X_complete = np.vstack((X_with_nan, X))
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X_complete)

array([[ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [153]:
X_complete

array([[  nan,  0.87,  1.31],
       [  nan, -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

# Handling Imbalanced Classes

In [154]:
# load libraries

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# Load iris data
iris = load_iris()

# create feature matrix
features = iris.data

# creat target vector
target = iris.target


In [155]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [156]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [157]:
# Remove first 40  observations
features = features[40:,:]
target = target[40:]

# create binary target vector indicating if class 0
target = np.where((target  == 0), 0, 1)

# look at the imbalanced target vector
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [158]:
# to balanance the imbalanced dataset

# create weights
weights = {0:0.9, 1:0.1}

# create random forest classifier with weights
RandomForestClassifier(class_weight=weights)

RandomForestClassifier(class_weight={0: 0.9, 1: 0.1})

In [159]:
# if you feel your dataset is balanced, then you can use the following

# train a random forest with balanced class weights
RandomForestClassifier(class_weight='balanced')

RandomForestClassifier(class_weight='balanced')

In [ ]:
# Down sampling and uosampling can be done for balamce the imbalamced data

# Down sampling will on the majarity data
# up sampling will be on the minority data 

In [160]:
# indices of each class observations

i_class0 = np.where(target == 0)[0]
i_class1 = np.where(target == 1)[0]

# Number of observations in each class

n_class0 = len(i_class0)
n_class1 = len(i_class1)

In [161]:
i_class0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [162]:
i_class1

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109], dtype=int64)

In [163]:
n_class = len(i_class0)
n_class

10

In [164]:
n_class = len(i_class1)
n_class

100

In [165]:
# for every observation of class o, randomly sample
# from class 1 without replacement

i_class1_downsampled = np.random.choice(i_class1, size=n_class0, replace=False)
i_class1_downsampled

array([ 65,  38,  77,  68,  86, 103,  71,  15,  91,  82], dtype=int64)

In [166]:
# Join together class 0's feature vector with the downloaded class 1's target vector

np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [167]:
# join together class 0's feature matrix with the downsampled class 1's feature matrix

np.vstack((features[i_class0,:], features[i_class1_downsampled,:]))

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6. , 2.9, 4.5, 1.5],
       [7.7, 3.8, 6.7, 2.2],
       [6.7, 2.5, 5.8, 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 2.8, 4.5, 1.3],
       [7.9, 3.8, 6.4, 2. ],
       [7.7, 2.8, 6.7, 2. ]])

In [168]:
# on the other option upsampling the minority class

# for every observation in class 1, randomly sample from class 0 with replacement
i_class0_upsampled = np.random.choice(i_class0, size=n_class1, replace=True)
i_class0_upsampled

array([5, 5, 1, 7, 6, 1, 7, 3, 8, 2, 0, 1, 7, 5, 4, 2, 1, 9, 3, 4, 9, 2,
       0, 9, 6, 3, 5, 8, 0, 2, 9, 1, 5, 7, 6, 4, 0, 0, 7, 2, 0, 7, 1, 0,
       6, 8, 8, 1, 9, 2, 6, 2, 9, 4, 9, 6, 2, 4, 1, 9, 0, 3, 7, 1, 9, 0,
       3, 7, 1, 7, 7, 5, 9, 4, 1, 9, 7, 5, 3, 3, 6, 4, 2, 2, 7, 1, 0, 4,
       4, 7, 6, 5, 1, 8, 8, 6, 7, 0, 8, 0], dtype=int64)

In [169]:
# join together class 0's unsampled target vector with class 1's target vector
np.concatenate((target[i_class0_upsampled], target[i_class1]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [170]:
# join together class 0's upsampled features matrix with class 1's feature matrix
np.vstack((features[i_class0_upsampled,:], features[i_class1,:]))

array([[4.8, 3. , 1.4, 0.3],
       [4.8, 3. , 1.4, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.3, 3.7, 1.5, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.3, 1.4, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.3, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [4.8, 3. , 1.4, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.8, 3. , 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [5.1, 3

In [171]:
# Join together class 0's feature vector with the downloaded class 1's target vector

np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [172]:
# Join together class 0's feature vector with the downloaded class 1's target vector

np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [173]:
# Join together class 0's feature vector with the downloaded class 1's target vector

np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [174]:
# Join together class 0's feature vector with the downloaded class 1's target vector

np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Handling Text Data

In [ ]:
# Cleaning the text


In [ ]:
# python's core string operations, in particular strip, replace, and split

In [ ]:
# create text

text_data = [' Interrobang. By Aishwarya Henriette ',
            'Parking And Going. By Karl Gautier',
            ' Today Is The night. By Jarek Prakash']

In [ ]:
# strip whitespaces
strip_whitespace = [i.strip() for i in text_data]

# show text
strip_whitespace

In [ ]:
for i in text_data:
    print(i.strip())
    

In [ ]:
# remove periods
remove_periods = [i.replace('.','') for i in strip_whitespace]

# show text
remove_periods

We also create and apply a custom transformation function

In [ ]:
# create function
def capitalizer(string: str) -> str:
    return string.upper()

# apply function
[capitalizer(string) for string in remove_periods]

In [ ]:
for i in remove_periods:
    print(i.upper())

In [ ]:
# finally, we can use regular expressions to make powerfull string operations

# Import library
import re

# create function
def replace_letters_with_X(string: str) -> str:
    return re.sub(r'[a-zA-Z]', 'X', string)

#apply function
[replace_letters_with_X(string) for string in remove_periods]

In [ ]:
# finally, we can use regular expressions to make powerfull string operations

# Import library
import re

# create function
def replace_letters_with_star(string: str) -> str:
    return re.sub(r'[a-zA-Z]', '*', string)

#apply function
[replace_letters_with_star(string) for string in remove_periods]

# Parsing and Cleaning HTML

You have a text data with HTML, elements and want to extract just the text. Use Beautiful Soup's extensive set of options to parse and extract from HTML.


In [4]:
pip install lxml

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install --upgrade pip

In [10]:
# load library
from bs4 import BeautifulSoup

# create some HTML code
html = '''
        <div class='ful_name'><span style='font-weight:bold'>
        Masego</span> Azra</div>
        '''

#parse html
soup = BeautifulSoup(html, 'lxml')

# find the div with the class 'full_name', show text
soup.find('div', {'class' : 'full_name'}).text

AttributeError: 'NoneType' object has no attribute 'text'

# Removing Punctuation

Define a function that uses translate with a dictionary of punctuation characters

In [12]:
# Load libraries
import unicodedata
import sys

# create a text
text_data = ['Hi!!!! I. Love. Song....',
            '10000% Agree!!!! #LoveIT',
             'Right?!?!']

# create a dictionary of punctuation characters
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
if unicodedata.category(chr(i)).startswith('P'))

             
             

In [13]:
punctuation

{33: None,
 34: None,
 35: None,
 37: None,
 38: None,
 39: None,
 40: None,
 41: None,
 42: None,
 44: None,
 45: None,
 46: None,
 47: None,
 58: None,
 59: None,
 63: None,
 64: None,
 91: None,
 92: None,
 93: None,
 95: None,
 123: None,
 125: None,
 161: None,
 167: None,
 171: None,
 182: None,
 183: None,
 187: None,
 191: None,
 894: None,
 903: None,
 1370: None,
 1371: None,
 1372: None,
 1373: None,
 1374: None,
 1375: None,
 1417: None,
 1418: None,
 1470: None,
 1472: None,
 1475: None,
 1478: None,
 1523: None,
 1524: None,
 1545: None,
 1546: None,
 1548: None,
 1549: None,
 1563: None,
 1566: None,
 1567: None,
 1642: None,
 1643: None,
 1644: None,
 1645: None,
 1748: None,
 1792: None,
 1793: None,
 1794: None,
 1795: None,
 1796: None,
 1797: None,
 1798: None,
 1799: None,
 1800: None,
 1801: None,
 1802: None,
 1803: None,
 1804: None,
 1805: None,
 2039: None,
 2040: None,
 2041: None,
 2096: None,
 2097: None,
 2098: None,
 2099: None,
 2100: None,
 2101: None,


In [14]:
# for each string, remove any puncuation characters
[string.translate(punctuation) for string in text_data]

['Hi I Love Song', '10000 Agree LoveIT', 'Right']

# NLTK : Natural Language Toolkit

# Tokenizing Text

Natural language toolkit for python(NLTK) has a powerful set of text manipulation operations, including word tokenzing.

In [15]:
# install the required package

import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Tamilarasu16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [16]:
# load libraries
from nltk.tokenize import word_tokenize

#create text
text = 'The science of today is the technology of tomorrow'

# tokenize words
word_tokenize(text)


['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [17]:
# We can also tokenize into sentences

# load library
from nltk.tokenize import sent_tokenize

# create text
text = 'The science of today is the technology of tomorrow. Tomorrow is today.'

# Tokenize sentences
sent_tokenize(text)

['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

# Removing Stop Words

In [18]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Tamilarasu16\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
# load library
from nltk.corpus import stopwords

# you will have to download set of stop words the first time
# import nltk
# nltk.download('stopwords')
# create word tokens

tokenized_words = ['i',
                  'am',
                  'going',
                  'to',
                  'go',
                  'to',
                  'the',
                  'store',
                  'and',
                  'park']

# Load stop words
stop_words = stopwords.words('english')
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [22]:
# remove stopwords
[word for word in tokenized_words if word not in stop_words]

['going', 'go', 'store', 'park']

In [23]:
[word for word in tokenized_words if word in stop_words]

['i', 'am', 'to', 'to', 'the', 'and']

# Stemmimng words

you have tokenized words and want to convert them into their root form

use NLTK's PorterStemmer


In [24]:
# Load library
from nltk.stem.porter import PorterStemmer

# create word tokens
tokenized_words = ['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']

# create stemmer
porter = PorterStemmer()

# apply stemmer
[porter.stem(word) for word in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

In [25]:
[porter.stem(i) for i in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

# Tagging Parts of Speech

In [2]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Tamilarasu16\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [7]:
# load libraries
from nltk import pos_tag
from nltk import word_tokenize

# create text data
text_data = 'Chris loved outdoor running'

# Use pre trained part of speech tagger
text_tagged = pos_tag(word_tokenize(text_data))

# show parts of speech
text_tagged

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]

In [8]:
# filter words
[word for word, tag in text_tagged if tag in ['NN', 'NNS', 'NNP', 'NNPS']]

['Chris']

A more realistic situation would be that we have data where every observation contains a tweet and we want to convert those sentences into features for indivudial parts of speech(e.g. a feature with 1 if a proper noun is present, and 0 otherwise) 

In [10]:
# create text
tweets = ['I am eating a burrito for breakfast',
         'Political science is an amaxing field',
         'San Fransisco is an awesome city']

# create list
tagged_tweets = []

# tag each word and each tweet
for i in tweets:
    tweet_tag = nltk.pos_tag(word_tokenize(i))
    tagged_tweets.append([tag for word, tag in tweet_tag])

In [11]:
tagged_tweets

[['PRP', 'VBP', 'VBG', 'DT', 'NN', 'IN', 'NN'],
 ['JJ', 'NN', 'VBZ', 'DT', 'JJ', 'NN'],
 ['NNP', 'NNP', 'VBZ', 'DT', 'JJ', 'NN']]

In [12]:
# use one hot encoding to convert the tags into features
from sklearn.preprocessing import MultiLabelBinarizer
one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)

array([[1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1]])

In [14]:
# show feature names
one_hot_multi.classes_

array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

In [15]:
import nltk
nltk.download('brown')

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\Tamilarasu16\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!


True

In [16]:
# load library
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger

# get some text from the brown corpus, broken into sentences
sentences = brown.tagged_sents(categories='news')
sentences

[[('The', 'AT'), ('Fulton', 'NP-TL'), ('County', 'NN-TL'), ('Grand', 'JJ-TL'), ('Jury', 'NN-TL'), ('said', 'VBD'), ('Friday', 'NR'), ('an', 'AT'), ('investigation', 'NN'), ('of', 'IN'), ("Atlanta's", 'NP$'), ('recent', 'JJ'), ('primary', 'NN'), ('election', 'NN'), ('produced', 'VBD'), ('``', '``'), ('no', 'AT'), ('evidence', 'NN'), ("''", "''"), ('that', 'CS'), ('any', 'DTI'), ('irregularities', 'NNS'), ('took', 'VBD'), ('place', 'NN'), ('.', '.')], [('The', 'AT'), ('jury', 'NN'), ('further', 'RBR'), ('said', 'VBD'), ('in', 'IN'), ('term-end', 'NN'), ('presentments', 'NNS'), ('that', 'CS'), ('the', 'AT'), ('City', 'NN-TL'), ('Executive', 'JJ-TL'), ('Committee', 'NN-TL'), (',', ','), ('which', 'WDT'), ('had', 'HVD'), ('over-all', 'JJ'), ('charge', 'NN'), ('of', 'IN'), ('the', 'AT'), ('election', 'NN'), (',', ','), ('``', '``'), ('deserves', 'VBZ'), ('the', 'AT'), ('praise', 'NN'), ('and', 'CC'), ('thanks', 'NNS'), ('of', 'IN'), ('the', 'AT'), ('City', 'NN-TL'), ('of', 'IN-TL'), ('Atlant

In [21]:
# split into 4000 sentences for training and 623 for testing
train = sentences[:4000]
test = sentences[4000:]

# create backoff tagger
unigram = UnigramTagger(train)
bigram = BigramTagger(train, backoff=unigram)
trigram = TrigramTagger(train, backoff=bigram)

# show acccuracy
trigram.evaluate(test)

C:\Users\Tamilarasu16\AppData\Local\Temp\ipykernel_9064\477503844.py:11: DeprecationWarning: 
  Function evaluate() has been deprecated.  Use accuracy(gold)
  instead.
  trigram.evaluate(test)


0.8174734002697437

# Encoding text as a bag of words

In [22]:
# load library 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# create text
text_data = np.array(['I Love Brazil. Brazil',
                     'Sweden is best',
                     'Germany beats both'])

# create the bag of words feature matrix
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

# show feature matrix
bag_of_words

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [23]:
bag_of_words.toarray()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

We can use the vocabulary_method to view the word associated with each feature

In [24]:
# show feature names
count.get_feature_names_out()

array(['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love',
       'sweden'], dtype=object)

In [25]:
# Create feature matrix with arguments
count_2gram = CountVectorizer(ngram_range=(1,2),
                             stop_words='english',
                             vocabulary=['brazil'])
bag = count_2gram.fit_transform(text_data)

# view feature matrix
bag.toarray()

# view the 1 gramand 2 gram
count_2gram.vocabulary_

{'brazil': 0}

# Generate the N-grams for the given sentence


In [26]:
import nltk
from nltk.util import ngrams

# function to generate n grams from sentences

def extract_n_grams(data, num):
    n_grams = ngrams(nltk.word_tokenize(data), num)
    return [ ' '.join(grams) for grams in n_grams]

data = 'A Class is a blueprint for the object.'

print('1-gram:', extract_n_grams(data, 1))
print('2-gram:', extract_n_grams(data, 2))
print('3-gram:', extract_n_grams(data, 3))
print('4-gram:', extract_n_grams(data, 4))



1-gram: ['A', 'Class', 'is', 'a', 'blueprint', 'for', 'the', 'object', '.']
2-gram: ['A Class', 'Class is', 'is a', 'a blueprint', 'blueprint for', 'for the', 'the object', 'object .']
3-gram: ['A Class is', 'Class is a', 'is a blueprint', 'a blueprint for', 'blueprint for the', 'for the object', 'the object .']
4-gram: ['A Class is a', 'Class is a blueprint', 'is a blueprint for', 'a blueprint for the', 'blueprint for the object', 'for the object .']


# Weighting word Importance

You want a bag of words, but with words weighted by their importance to an observation.

Compare the frequency of the word in a document(a tweet, movie review, speech transcript,etc.) with the frequency of the word in all other documents using term frequency-inverse document frequency (tf-idf) scikit-learn makes this easy with TfidVectorizer.

In [27]:
# load libraries
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# create text
text_data = np.array(['I Love Brazil. Brazil',
                     'Sweden is best',
                     'Germany beats both'])

# create the tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

# show tf-idf feature matrix
feature_matrix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [29]:
# Show tf-idf feature matrix as dense matrix
feature_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

Vocabulary_shows us the word of each feature

In [30]:
# show feature names
tfidf.vocabulary_

{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

# Handling Dates and Times

# Converting Strings to Dates

Given a vector of strings representing dates and times, you want to transform them into time series data

Use pandas to_dateframe with the format of the date and/or time specified in the format parameter

In [39]:
# load libraries

import numpy as np
import pandas as pd
from datetime import datetime

# create strings
date_strings = np.array(['03-04-2005 11:35 PM',
                        '23-05-2010 12:01 AM',
                        '04-09-2009 09:09 PM'])

In [42]:
# convert to datetimes
[pd.to_datetime(date, format='%d-%m-%y %I:%M %p') for date in date_strings]

ValueError: time data '03-04-2005 11:35 PM' does not match format '%d-%m-%y %I:%M %p' (match)

We might also want to add an argument to the errors parameters to handle problems

In [41]:
# convert to datetimes
[pd.to_datetime(date, format='%d-%m-%y %I:%M:%p', errors='coerce')
for date in date_strings]

[NaT, NaT, NaT]

# Handling Time Zones

you have time series data and want to add or change time zone information.

If not specified, pandas objects have no time zone. However, we can add a time zone using tz during creation.


In [43]:
# load library
import pandas as pd

# create datetime
pd.Timestamp('2017-05-01 06:00:00', tz='Europe/London')

Timestamp('2017-05-01 06:00:00+0100', tz='Europe/London')

In [44]:
# create datetime
date=pd.Timestamp('2017-05-01 06:00:00')

# set time zone
date_in_london = date.tz_localize('Europe/London')

# show datetime
date_in_london

Timestamp('2017-05-01 06:00:00+0100', tz='Europe/London')

We can also convert to a different time zone

In [45]:
# change time zone
date_in_london.tz_convert('Africa/Abidjan')

Timestamp('2017-05-01 05:00:00+0000', tz='Africa/Abidjan')

Finally, pandas'Series objects can apply tz_localize and tz_convert to every element

In [46]:
# create three dates
dates = pd.Series(pd.date_range('2/2/2002', periods=3, freq='M'))

In [47]:
dates

0   2002-02-28
1   2002-03-31
2   2002-04-30
dtype: datetime64[ns]

In [49]:
# Set time zone
dates.dt.tz_localize('Africa/Abidjan')

0   2002-02-28 00:00:00+00:00
1   2002-03-31 00:00:00+00:00
2   2002-04-30 00:00:00+00:00
dtype: datetime64[ns, Africa/Abidjan]

Pandas support two sets of strings representing timezones, however I suggest using pytz library's string. We can see all the strings used to represent time zones by importing all_timezones 

In [50]:
# load libraries
from pytz import all_timezones

# see time zones
all_timezones

['Africa/Abidjan',
 'Africa/Accra',
 'Africa/Addis_Ababa',
 'Africa/Algiers',
 'Africa/Asmara',
 'Africa/Asmera',
 'Africa/Bamako',
 'Africa/Bangui',
 'Africa/Banjul',
 'Africa/Bissau',
 'Africa/Blantyre',
 'Africa/Brazzaville',
 'Africa/Bujumbura',
 'Africa/Cairo',
 'Africa/Casablanca',
 'Africa/Ceuta',
 'Africa/Conakry',
 'Africa/Dakar',
 'Africa/Dar_es_Salaam',
 'Africa/Djibouti',
 'Africa/Douala',
 'Africa/El_Aaiun',
 'Africa/Freetown',
 'Africa/Gaborone',
 'Africa/Harare',
 'Africa/Johannesburg',
 'Africa/Juba',
 'Africa/Kampala',
 'Africa/Khartoum',
 'Africa/Kigali',
 'Africa/Kinshasa',
 'Africa/Lagos',
 'Africa/Libreville',
 'Africa/Lome',
 'Africa/Luanda',
 'Africa/Lubumbashi',
 'Africa/Lusaka',
 'Africa/Malabo',
 'Africa/Maputo',
 'Africa/Maseru',
 'Africa/Mbabane',
 'Africa/Mogadishu',
 'Africa/Monrovia',
 'Africa/Nairobi',
 'Africa/Ndjamena',
 'Africa/Niamey',
 'Africa/Nouakchott',
 'Africa/Ouagadougou',
 'Africa/Porto-Novo',
 'Africa/Sao_Tome',
 'Africa/Timbuktu',
 'Africa/

# Selecting Dates and Times

You have a vector of dates and you want to select one or more

In [56]:
# load library
import pandas as pd

# create dataframe
dataframe = pd.DataFrame()

# Create datetimes
dataframe['date'] = pd.date_range('1/1/2001', periods = 100000, freq = 'H')
dataframe

date
0     2001-01-01 00:00:00
1     2001-01-01 01:00:00
2     2001-01-01 02:00:00
3     2001-01-01 03:00:00
4     2001-01-01 04:00:00
...                   ...
99995 2012-05-29 11:00:00
99996 2012-05-29 12:00:00
99997 2012-05-29 13:00:00
99998 2012-05-29 14:00:00
99999 2012-05-29 15:00:00

[100000 rows x 1 columns]

In [58]:
# select observations between two datetimes
dataframe[(dataframe['date'] > '2002-1-1 01:00:00') & (dataframe['date'] <= '2002-1-1-04:00:00')]

date
8762 2002-01-01 02:00:00
8763 2002-01-01 03:00:00
8764 2002-01-01 04:00:00

Alternatively we can set the date column as the Dataframe's index and then slice using loc

In [59]:
# Set index
dataframe = dataframe.set_index(dataframe['date'])
dataframe

date
date                                   
2001-01-01 00:00:00 2001-01-01 00:00:00
2001-01-01 01:00:00 2001-01-01 01:00:00
2001-01-01 02:00:00 2001-01-01 02:00:00
2001-01-01 03:00:00 2001-01-01 03:00:00
2001-01-01 04:00:00 2001-01-01 04:00:00
...                                 ...
2012-05-29 11:00:00 2012-05-29 11:00:00
2012-05-29 12:00:00 2012-05-29 12:00:00
2012-05-29 13:00:00 2012-05-29 13:00:00
2012-05-29 14:00:00 2012-05-29 14:00:00
2012-05-29 15:00:00 2012-05-29 15:00:00

[100000 rows x 1 columns]

In [60]:
# select observations between two datetimes
dataframe.loc['2002-1-1 01:00:00':'2002-1-1 04:00:00']

date
date                                   
2002-01-01 01:00:00 2002-01-01 01:00:00
2002-01-01 02:00:00 2002-01-01 02:00:00
2002-01-01 03:00:00 2002-01-01 03:00:00
2002-01-01 04:00:00 2002-01-01 04:00:00

# Breaking Up date data into multiple features

You have a column of dates and times and you want to create features for year, month,day and minute

Use Pandas Series.dt's time properties

In [61]:
# Load library
import pandas as pd

# create dataframe
dataframe = pd.DataFrame()

# create five dates
dataframe['dates'] = pd.date_range('1/1/2001', periods=150, freq='W')
dataframe

dates
0   2001-01-07
1   2001-01-14
2   2001-01-21
3   2001-01-28
4   2001-02-04
..         ...
145 2003-10-19
146 2003-10-26
147 2003-11-02
148 2003-11-09
149 2003-11-16

[150 rows x 1 columns]

In [65]:
# create features for year,month,dat,hour and minute
dataframe['year'] = dataframe['dates'].dt.year
dataframe['month'] = dataframe['dates'].dt.month
dataframe['day'] = dataframe['dates'].dt.day
dataframe['hour'] = dataframe['dates'].dt.hour
dataframe['minute'] = dataframe['dates'].dt.minute

dataframe

dates  year  month  day  hour  minute
0   2001-01-07  2001      1    7     0       0
1   2001-01-14  2001      1   14     0       0
2   2001-01-21  2001      1   21     0       0
3   2001-01-28  2001      1   28     0       0
4   2001-02-04  2001      2    4     0       0
..         ...   ...    ...  ...   ...     ...
145 2003-10-19  2003     10   19     0       0
146 2003-10-26  2003     10   26     0       0
147 2003-11-02  2003     11    2     0       0
148 2003-11-09  2003     11    9     0       0
149 2003-11-16  2003     11   16     0       0

[150 rows x 6 columns]

# Calculating the difference between dates

You have two datetime features and want to calculate the time between them for each observation

subtract the two data features using pandas


In [67]:
# load library
import pandas as pd

# Create data frame
dataframe = pd.DataFrame()

# create two datetime features
dataframe['Arrived'] = [pd.Timestamp('01-01-2017'), pd.Timestamp('01-04-2017')]
dataframe['Left'] = [pd.Timestamp('01-01-2017'), pd.Timestamp('01-06-2017')]

# calculate duration between features
dataframe['Left'] - dataframe['Arrived']

0   0 days
1   2 days
dtype: timedelta64[ns]

In [68]:
dataframe

Arrived       Left
0 2017-01-01 2017-01-01
1 2017-01-04 2017-01-06

In [70]:
# calculate duration between features
pd.Series(delta.days for delta in (dataframe['Left'] - dataframe['Arrived']))

0    0
1    2
dtype: int64

# Encoding Days of the Week

you have a vector of dates and want to know the day of the week for each date.
use pandas Series.dt property weekday_name.


In [77]:
# load library
import pandas as pd

#Create dates
dates = pd.Series(pd.date_range('2/2/2002',periods=3, freq='M'))

# show days of the week
dates.dt.weekday_name

AttributeError: 'DatetimeProperties' object has no attribute 'weekday_name'

In [76]:
dates

0   2002-02-28
1   2002-03-31
2   2002-04-30
dtype: datetime64[ns]

In [78]:
dates.dt.weekday

0    3
1    6
2    1
dtype: int64

# Creating a lagged Feature

you want to create a feature that is lagged n time periods
use pandas's shift.

In [79]:
# load library
import pandas as pd

# create dataframe
dataframe = pd.DataFrame()

# Create data
dataframe['dates'] = pd.date_range('1/1/2001', periods=5, freq='D')
dataframe['stock_price'] = [1.1,2.2,3.3,4.4,5.5]

# lagged values by one row
dataframe['previous_days_stock_price'] = dataframe['stock_price'].shift(1)

# show dataframe
dataframe

dates  stock_price  previous_days_stock_price
0 2001-01-01          1.1                        NaN
1 2001-01-02          2.2                        1.1
2 2001-01-03          3.3                        2.2
3 2001-01-04          4.4                        3.3
4 2001-01-05          5.5                        4.4

# Using Rolling Time Windows 

In [ ]:
Given time series data, you want to calculate some statistic fro a rolling time.

In [80]:
# load library 
import pandas as pd

# create datetimes
time_index = pd.date_range('01/01/2010', periods=5, freq='M')

# create data frame, set index
dataframe = pd.DataFrame(index=time_index)

# create feature
dataframe['Stock_price'] = [1,2,3,4,5]


In [81]:
dataframe

Stock_price
2010-01-31            1
2010-02-28            2
2010-03-31            3
2010-04-30            4
2010-05-31            5

In [82]:
# calculate rolling mean
dataframe.rolling(window=2).mean()


Stock_price
2010-01-31          NaN
2010-02-28          1.5
2010-03-31          2.5
2010-04-30          3.5
2010-05-31          4.5

In [85]:
# calculate rolling mean
dataframe.rolling(window=6).mean()


Stock_price
2010-01-31          NaN
2010-02-28          NaN
2010-03-31          NaN
2010-04-30          NaN
2010-05-31          NaN

# handling missing data in time series

In [ ]:
you can interpolation function to solve this

In [86]:
# load library
import pandas as pd 
import numpy as np

#create date
time_index = pd.date_range('01/01/2010', periods=5, freq='M')

In [87]:
time_index

DatetimeIndex(['2010-01-31', '2010-02-28', '2010-03-31', '2010-04-30',
               '2010-05-31'],
              dtype='datetime64[ns]', freq='M')

In [88]:
# create dataframe, set index
dataframe = pd.DataFrame(index=time_index)

# create feature with a gap of missing values
dataframe['Sales'] = [1.0, 2.0, np.nan, np.nan, 5.0]

In [89]:
dataframe

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    NaN
2010-04-30    NaN
2010-05-31    5.0

In [90]:
# interpolate missing values
dataframe.interpolate()

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    3.0
2010-04-30    4.0
2010-05-31    5.0

Alternatively we can replace missing values with the last known value(i.e) forwardfilling 

In [91]:
# forward filling
dataframe.ffill()

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    2.0
2010-04-30    2.0
2010-05-31    5.0

In [93]:
# We can also use backward filling

dataframe.bfill()

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    5.0
2010-04-30    5.0
2010-05-31    5.0

In [94]:
# interpolate misssing values
dataframe.interpolate(methods = 'quadratic')

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    3.0
2010-04-30    4.0
2010-05-31    5.0

In [95]:
# interpolate misssing values
dataframe.interpolate(methods = 'pad')

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    3.0
2010-04-30    4.0
2010-05-31    5.0

In [96]:
# you can also give limit in interpolate

dataframe.interpolate(limit=1, limit_direction='forward')

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    3.0
2010-04-30    NaN
2010-05-31    5.0

In [97]:
# you can also give limit in interpolate

dataframe.interpolate(limit=1, limit_direction='backward')

Sales
2010-01-31    1.0
2010-02-28    2.0
2010-03-31    NaN
2010-04-30    4.0
2010-05-31    5.0